language: node_js
node_js:
  - "6"
before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3 # give xvfb some time to start
script:
  - npm run check
after_success:
  - "cat coverage/lcov.info | coveralls --verbose"
cache:
  directories:
  - $HOME/.npm
  - node_modules
addons:
  firefox: "latest"
# Get a sudo-enabled vm for more ram (7.5 GB vs. 4 GB). Firefox tests run on travis seem to
# require more than 4.
sudo: required
